REVIEWS := ROBINSON-GUNNING-NEIMHIN-16321701-CS7IS4-REVIEW-GROUP2.txt ROBINSON-GUNNING-NEIMHIN-16321701-CS7IS4-REVIEW-GROUP5.txt ROBINSON-GUNNING-NEIMHIN-16321701-CS7IS4-REVIEW-GROUP6.txt ROBINSON-GUNNING-NEIMHIN-16321701-CS7IS4-REVIEW-GROUP10.txt # These should be aggregated into a zip file and uploaded via Blackboard,
# adhering to the naming conventions described below for the individual
# files.  The zip file should be named using the convention:
# SURNAME-FIRSTNAME-STUDENTNUMBER-CS7IS4-PEER-REVIEWS.zip
# as described in the first set of lecture notes.

ROBINSON-GUNNING-NEIMHIN-16321701-CS7IS4-PEER-REVIEWS.zip:  $(REVIEWS)
	zip $@ $^
