all-exps: exp/1.touch exp/8.touch exp/16.touch exp/32.touch exp/64.touch exp/128.touch exp/256.touch exp/1024.touch exp/2048.touch exp/4096.touch

exp/4096.touch: exp/4096/0 exp/4096/1 exp/4096/2 exp/4096/3 exp/4096/4

exp/4096/0:
	python src/baseline.py --run-name 0 --fold 0 --batch-size 4096
exp/4096/1:
	python src/baseline.py --run-name 1 --fold 1 --batch-size 4096
exp/4096/2:
	python src/baseline.py --run-name 2 --fold 2 --batch-size 4096
exp/4096/3:
	python src/baseline.py --run-name 3 --fold 3 --batch-size 4096
exp/4096/4:
	python src/baseline.py --run-name 4 --fold 4 --batch-size 4096

exp/2048.touch: exp/2048/0 exp/2048/1 exp/2048/2 exp/2048/3 exp/2048/4

exp/2048/0:
	python src/baseline.py --run-name 0 --fold 0 --batch-size 2048
exp/2048/1:                                          
	python src/baseline.py --run-name 1 --fold 1 --batch-size 2048
exp/2048/2:                                          
	python src/baseline.py --run-name 2 --fold 2 --batch-size 2048
exp/2048/3:                                          
	python src/baseline.py --run-name 3 --fold 3 --batch-size 2048
exp/2048/4:                                          
	python src/baseline.py --run-name 4 --fold 4 --batch-size 2048

exp/1024.touch: exp/1024/0 exp/1024/1 exp/1024/2 exp/1024/3 exp/1024/4

exp/1024/0:
	python src/baseline.py --run-name 0 --fold 0 --batch-size 1024
exp/1024/1:                                          
	python src/baseline.py --run-name 1 --fold 1 --batch-size 1024
exp/1024/2:                                          
	python src/baseline.py --run-name 2 --fold 2 --batch-size 1024
exp/1024/3:                                          
	python src/baseline.py --run-name 3 --fold 3 --batch-size 1024
exp/1024/4:                                          
	python src/baseline.py --run-name 4 --fold 4 --batch-size 1024

exp/512.touch: exp/512/0 exp/512/1 exp/512/2 exp/512/3 exp/512/4

exp/512/0:
	python src/baseline.py --run-name 0 --fold 0 --batch-size 512
exp/512/1:                                           
	python src/baseline.py --run-name 1 --fold 1 --batch-size 512
exp/512/2:                                           
	python src/baseline.py --run-name 2 --fold 2 --batch-size 512
exp/512/3:                                           
	python src/baseline.py --run-name 3 --fold 3 --batch-size 512
exp/512/4:                                           
	python src/baseline.py --run-name 4 --fold 4 --batch-size 512

exp/256.touch: exp/256/0 exp/256/1 exp/256/2 exp/256/3 exp/256/4

exp/256/0:
	python src/baseline.py --run-name 0 --fold 0 --batch-size 256
exp/256/1:                                           
	python src/baseline.py --run-name 1 --fold 1 --batch-size 256
exp/256/2:                                           
	python src/baseline.py --run-name 2 --fold 2 --batch-size 256
exp/256/3:                                           
	python src/baseline.py --run-name 3 --fold 3 --batch-size 256
exp/256/4:                                           
	python src/baseline.py --run-name 4 --fold 4 --batch-size 256

exp/128.touch: exp/128/0 exp/128/1 exp/128/2 exp/128/3 exp/128/4

exp/128/0:
	python src/baseline.py --run-name 0 --fold 0 --batch-size 128
exp/128/1:                                           
	python src/baseline.py --run-name 1 --fold 1 --batch-size 128
exp/128/2:                                           
	python src/baseline.py --run-name 2 --fold 2 --batch-size 128
exp/128/3:                                           
	python src/baseline.py --run-name 3 --fold 3 --batch-size 128
exp/128/4:                                           
	python src/baseline.py --run-name 4 --fold 4 --batch-size 128

exp/64.touch: exp/64/0 exp/64/1 exp/64/2 exp/64/3 exp/64/4

exp/64/0:
	python src/baseline.py --run-name 0 --fold 0 --batch-size 64
exp/64/1:                                           
	python src/baseline.py --run-name 1 --fold 1 --batch-size 64
exp/64/2:                                           
	python src/baseline.py --run-name 2 --fold 2 --batch-size 64
exp/64/3:                                           
	python src/baseline.py --run-name 3 --fold 3 --batch-size 64
exp/64/4:                                           
	python src/baseline.py --run-name 4 --fold 4 --batch-size 64

exp/32.touch: exp/32/0 exp/32/1 exp/32/2 exp/32/3 exp/32/4

exp/32/0:
	python src/baseline.py --run-name 0 --fold 0 --batch-size 32
exp/32/1:                                           
	python src/baseline.py --run-name 1 --fold 1 --batch-size 32
exp/32/2:                                           
	python src/baseline.py --run-name 2 --fold 2 --batch-size 32
exp/32/3:                                           
	python src/baseline.py --run-name 3 --fold 3 --batch-size 32
exp/32/4:                                           
	python src/baseline.py --run-name 4 --fold 4 --batch-size 32

exp/16.touch: exp/16/0 exp/16/1 exp/16/2 exp/16/3 exp/16/4

exp/16/0:
	python src/baseline.py --run-name 0 --fold 0 --batch-size 16
exp/16/1:                                           
	python src/baseline.py --run-name 1 --fold 1 --batch-size 16
exp/16/2:                                           
	python src/baseline.py --run-name 2 --fold 2 --batch-size 16
exp/16/3:                                           
	python src/baseline.py --run-name 3 --fold 3 --batch-size 16
exp/16/4:                                           
	python src/baseline.py --run-name 4 --fold 4 --batch-size 16

exp/8.touch: exp/8/0 exp/8/1 exp/8/2 exp/8/3 exp/8/4

exp/8/0:
	python src/baseline.py --run-name 0 --fold 0 --batch-size 8
exp/8/1:                                           
	python src/baseline.py --run-name 1 --fold 1 --batch-size 8
exp/8/2:                                           
	python src/baseline.py --run-name 2 --fold 2 --batch-size 8
exp/8/3:                                           
	python src/baseline.py --run-name 3 --fold 3 --batch-size 8
exp/8/4:                                           
	python src/baseline.py --run-name 4 --fold 4 --batch-size 8

exp/1.touch: exp/1/0 exp/1/1 exp/1/2 exp/1/3 exp/1/4

exp/1/0:
	python src/baseline.py --run-name 0 --fold 0 --batch-size 1
exp/1/1:                                           
	python src/baseline.py --run-name 1 --fold 1 --batch-size 1
exp/1/2:                                           
	python src/baseline.py --run-name 2 --fold 2 --batch-size 1
exp/1/3:                                           
	python src/baseline.py --run-name 3 --fold 3 --batch-size 1
exp/1/4:                                           
	python src/baseline.py --run-name 4 --fold 4 --batch-size 1

SRC_DIR := src
TMP_DIR := tmp
OUTPUT_DIR := output
PYTHON_FILES := $(wildcard $(SRC_DIR)/*.py)
PDF_FILES := $(addprefix $(TMP_DIR)/,$(notdir $(PYTHON_FILES:.py=.pdf)))
tmp/all-source.pdf: $(PDF_FILES)
	@pdfunite $^ $@

$(TMP_DIR)/%.pdf: $(SRC_DIR)/%.py
	@mkdir -p $(TMP_DIR)
	@enscript -M A3 --line-numbers -Epython --color --pretty-print -p - $< | ps2pdf - - | pdfcrop - $@

